# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GAM Header Bidding Demo - ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GAM Header Bidding Demo - ObjC
  pod 'GoogleMobileAds-HyBid-Adapters', '2.19.0.0'
end
